"""fix

Revision ID: 207e1e3df617
Revises: 
Create Date: 2024-07-22 16:05:31.546163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207e1e3df617'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('body_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_weight', sa.FLOAT(), nullable=True))

    op.create_table('weight_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_weight_entries_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
