"""added new model 'set' t

Revision ID: 4ab70660460f
Revises: 
Create Date: 2024-07-22 10:02:44.347888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab70660460f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('reps')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reps', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
