"""added foods model

Revision ID: 65a8a6dc7982
Revises: 7bb694e47a2e
Create Date: 2024-07-29 12:36:25.862357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a8a6dc7982'
down_revision = '7bb694e47a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caloric_goal', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('caloric_goal')

    # ### end Alembic commands ###
