"""updated body weight model

Revision ID: 7bb694e47a2e
Revises: 207e1e3df617
Create Date: 2024-07-22 18:36:38.871252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb694e47a2e'
down_revision = '207e1e3df617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_weights', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_weights', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
